# Generated by Django 5.2.7 on 2025-11-04 12:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contracts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaiementApporteur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "montant_a_payer",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Montant dû par l'apporteur = net à reverser",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Montant à payer",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("EN_ATTENTE", "En attente"), ("PAYE", "Payé")],
                        default="EN_ATTENTE",
                        max_length=12,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "methode_paiement",
                    models.CharField(
                        blank=True,
                        choices=[("OM", "Orange Money"), ("WAVE", "Wave")],
                        max_length=8,
                        verbose_name="Méthode de paiement",
                    ),
                ),
                (
                    "reference_transaction",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Référence transaction"
                    ),
                ),
                (
                    "numero_compte",
                    models.CharField(
                        blank=True,
                        help_text="N° OM ou Wave fourni par l'apporteur",
                        max_length=32,
                        verbose_name="N° compte/Wallet déclarant",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes internes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "contrat",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encaissement",
                        to="contracts.contrat",
                        verbose_name="Contrat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Encaissement apporteur",
                "verbose_name_plural": "Encaissements apporteurs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoriquePaiement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATION", "Création"),
                            ("STATUS_CHANGE", "Changement de statut"),
                            ("VALIDATION", "Validation paiement"),
                            ("MODIFICATION", "Modification"),
                        ],
                        max_length=32,
                        verbose_name="Action",
                    ),
                ),
                ("details", models.TextField(blank=True, verbose_name="Détails")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Horodatage"),
                ),
                (
                    "effectue_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Effectué par",
                    ),
                ),
                (
                    "paiement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historiques",
                        to="payments.paiementapporteur",
                        verbose_name="Encaissement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique encaissement",
                "verbose_name_plural": "Historiques encaissements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="paiementapporteur",
            index=models.Index(fields=["status"], name="payments_pa_status_1fa1ea_idx"),
        ),
    ]
