# Generated by Django 5.2.6 on 2025-12-02 10:25

import django.core.validators
import django.db.models.deletion
import re
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contracts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaiementApporteur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "montant_a_payer",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Prime TTC - commission apporteur",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Montant à payer",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En attente"),
                            ("PAYE", "Payé"),
                            ("ANNULE", "Annulé"),
                        ],
                        default="EN_ATTENTE",
                        max_length=12,
                    ),
                ),
                (
                    "methode_paiement",
                    models.CharField(
                        blank=True,
                        choices=[("OM", "Orange Money"), ("WAVE", "Wave")],
                        max_length=8,
                    ),
                ),
                (
                    "reference_transaction",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Référence alphanumérique de 6-64 caractères",
                                regex="^[A-Z0-9-]{6,64}$",
                            )
                        ],
                    ),
                ),
                (
                    "numero_compte",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Numéro de 9 chiffres requis",
                                regex=re.compile("^\\d{9}$"),
                            )
                        ],
                        verbose_name="N° compte/Wallet",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contrat",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encaissement",
                        to="contracts.contrat",
                        verbose_name="Contrat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Encaissement apporteur",
                "verbose_name_plural": "Encaissements apporteurs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoriquePaiement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATION", "Création"),
                            ("STATUS_CHANGE", "Changement de statut"),
                            ("VALIDATION", "Validation paiement"),
                            ("MODIFICATION", "Modification"),
                        ],
                        max_length=32,
                    ),
                ),
                ("details", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "effectue_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paiement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historiques",
                        to="payments.paiementapporteur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique encaissement",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="paiementapporteur",
            index=models.Index(fields=["status"], name="payments_pa_status_1fa1ea_idx"),
        ),
        migrations.AddIndex(
            model_name="paiementapporteur",
            index=models.Index(
                fields=["contrat", "status"], name="payments_pa_contrat_fe47b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paiementapporteur",
            index=models.Index(
                fields=["created_at"], name="payments_pa_created_5fba9b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="paiementapporteur",
            constraint=models.CheckConstraint(
                condition=models.Q(("montant_a_payer__gte", Decimal("0.00"))),
                name="paiement_montant_non_negatif",
            ),
        ),
        migrations.AddConstraint(
            model_name="paiementapporteur",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["EN_ATTENTE", "PAYE", "ANNULE"])),
                name="status_paiement_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="historiquepaiement",
            index=models.Index(
                fields=["paiement", "-created_at"],
                name="payments_hi_paiemen_48c128_idx",
            ),
        ),
    ]
