# Generated by Django 5.2.6 on 2025-09-22 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementApporteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_commission', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant commission')),
                ('montant_verse', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Montant versé à l'admin")),
                ('methode_paiement', models.CharField(blank=True, choices=[('WAVE', 'Wave'), ('ORANGE_MONEY', 'Orange Money'), ('CASH', 'Espèces'), ('VIREMENT', 'Virement bancaire')], max_length=20, null=True, verbose_name='Méthode de paiement')),
                ('status', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PAYE', 'Payé'), ('ANNULE', 'Annulé'), ('ECHEC', 'Échec')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('reference_transaction', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Référence de transaction')),
                ('numero_compte', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de compte (Wave/OM)')),
                ('date_paiement', models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('contrat', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='paiement_apporteur', to='contracts.contrat', verbose_name='Contrat')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Paiement Apporteur',
                'verbose_name_plural': 'Paiements Apporteurs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoriquePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATION', 'Création'), ('MODIFICATION', 'Modification'), ('VALIDATION', 'Validation'), ('ANNULATION', 'Annulation'), ('ECHEC', 'Échec de paiement')], max_length=20, verbose_name='Action')),
                ('details', models.TextField(blank=True, verbose_name='Détails')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('effectue_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Effectué par')),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='payments.paiementapporteur', verbose_name='Paiement')),
            ],
            options={
                'verbose_name': 'Historique de paiement',
                'verbose_name_plural': 'Historiques de paiements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecapitulatifCommissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.DateField(verbose_name='Mois')),
                ('nombre_contrats', models.IntegerField(default=0, verbose_name='Nombre de contrats')),
                ('total_primes_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total primes TTC')),
                ('total_commissions', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total commissions')),
                ('total_verse', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total versé')),
                ('total_en_attente', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total en attente')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('apporteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recapitulatifs', to=settings.AUTH_USER_MODEL, verbose_name='Apporteur')),
            ],
            options={
                'verbose_name': 'Récapitulatif commissions',
                'verbose_name_plural': 'Récapitulatifs commissions',
                'ordering': ['-mois'],
            },
        ),
        migrations.AddIndex(
            model_name='paiementapporteur',
            index=models.Index(fields=['status'], name='payments_pa_status_1fa1ea_idx'),
        ),
        migrations.AddIndex(
            model_name='paiementapporteur',
            index=models.Index(fields=['date_paiement'], name='payments_pa_date_pa_473ffd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recapitulatifcommissions',
            unique_together={('apporteur', 'mois')},
        ),
    ]
