# Generated by Django 5.2.6 on 2025-11-10 13:08

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0002_alter_client_adresse_alter_client_telephone_and_more"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paiementapporteur",
            name="montant_a_payer",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Montant dû par l'apporteur à BWHITE (Prime TTC - sa commission)",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Montant à payer",
            ),
        ),
        migrations.AlterField(
            model_name="paiementapporteur",
            name="status",
            field=models.CharField(
                choices=[
                    ("EN_ATTENTE", "En attente"),
                    ("PAYE", "Payé"),
                    ("ANNULE", "Annulé"),
                ],
                default="EN_ATTENTE",
                max_length=12,
                verbose_name="Statut",
            ),
        ),
        migrations.AddConstraint(
            model_name="paiementapporteur",
            constraint=models.CheckConstraint(
                condition=models.Q(("montant_a_payer__gte", Decimal("0.00"))),
                name="paiement_montant_non_negatif",
            ),
        ),
    ]
