# Generated by Django 5.2.6 on 2025-12-06 10:41

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paiementapporteur",
            name="methode_paiement",
            field=models.CharField(
                blank=True,
                help_text="Renseignée automatiquement par Bictorys ou lors d'une validation manuelle.",
                max_length=50,
                verbose_name="Méthode utilisée",
            ),
        ),
        migrations.AlterField(
            model_name="paiementapporteur",
            name="montant_a_payer",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Net à reverser (contrat.net_a_reverser).",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Montant à payer",
            ),
        ),
        migrations.AlterField(
            model_name="paiementapporteur",
            name="numero_compte",
            field=models.CharField(
                blank=True,
                help_text="Éventuellement rempli par Bictorys (numéro de téléphone, wallet, etc.).",
                max_length=32,
                verbose_name="N° compte/Wallet",
            ),
        ),
        migrations.AlterField(
            model_name="paiementapporteur",
            name="reference_transaction",
            field=models.CharField(
                blank=True,
                help_text="ID ou référence de transaction renvoyée par Bictorys / la banque.",
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Référence alphanumérique de 6-64 caractères.",
                        regex="^[0-9A-Za-z-]{6,64}$",
                    )
                ],
            ),
        ),
    ]
