# Generated by Django 5.2.6 on 2025-11-23 11:51

import django.core.validators
import django.db.models.deletion
import re
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0005_client_telephone_secondaire_alter_client_telephone"),
        ("payments", "0002_alter_paiementapporteur_montant_a_payer_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historiquepaiement",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Historique encaissement",
            },
        ),
        migrations.AlterField(
            model_name="historiquepaiement",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATION", "Création"),
                    ("STATUS_CHANGE", "Changement de statut"),
                    ("VALIDATION", "Validation paiement"),
                    ("MODIFICATION", "Modification"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="historiquepaiement",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="historiquepaiement",
            name="details",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="historiquepaiement",
            name="effectue_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="historiquepaiement",
            name="paiement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historiques",
                to="payments.paiementapporteur",
            ),
        ),
        migrations.AlterField(
            model_name="paiementapporteur",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="paiementapporteur",
            name="methode_paiement",
            field=models.CharField(
                blank=True,
                choices=[("OM", "Orange Money"), ("WAVE", "Wave")],
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="paiementapporteur",
            name="montant_a_payer",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Prime TTC - commission apporteur",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Montant à payer",
            ),
        ),
        migrations.AlterField(
            model_name="paiementapporteur",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="paiementapporteur",
            name="numero_compte",
            field=models.CharField(
                blank=True,
                max_length=32,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Numéro de 9 chiffres requis",
                        regex=re.compile("^\\d{9}$"),
                    )
                ],
                verbose_name="N° compte/Wallet",
            ),
        ),
        migrations.AlterField(
            model_name="paiementapporteur",
            name="reference_transaction",
            field=models.CharField(
                blank=True,
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Référence alphanumérique de 6-64 caractères",
                        regex="^[A-Z0-9-]{6,64}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="paiementapporteur",
            name="status",
            field=models.CharField(
                choices=[
                    ("EN_ATTENTE", "En attente"),
                    ("PAYE", "Payé"),
                    ("ANNULE", "Annulé"),
                ],
                default="EN_ATTENTE",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="paiementapporteur",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name="historiquepaiement",
            index=models.Index(
                fields=["paiement", "-created_at"],
                name="payments_hi_paiemen_48c128_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paiementapporteur",
            index=models.Index(
                fields=["contrat", "status"], name="payments_pa_contrat_fe47b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paiementapporteur",
            index=models.Index(
                fields=["created_at"], name="payments_pa_created_5fba9b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="paiementapporteur",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["EN_ATTENTE", "PAYE", "ANNULE"])),
                name="status_paiement_valid",
            ),
        ),
    ]
