# Generated by Django 5.2.6 on 2025-09-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='commission_askia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Commission Askia'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='date_echeance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='date_effet',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='duree',
            field=models.PositiveIntegerField(default=12),
        ),
    ]
