# Generated by Django 5.2.6 on 2025-11-10 13:08

import contracts.validators
import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="adresse",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.MinLengthValidator(
                        2, message="Adresse trop courte (2 caractères minimum)"
                    )
                ],
                verbose_name="Adresse",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="telephone",
            field=models.CharField(
                max_length=9,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Le numéro doit être au format sénégalais (ex: 771234567)",
                        regex="^(70|71|75|76|77|78|30|33|34)\\d{7}$",
                    )
                ],
                verbose_name="Téléphone",
            ),
        ),
        migrations.AlterField(
            model_name="contrat",
            name="status",
            field=models.CharField(
                choices=[
                    ("SIMULATION", "Simulation"),
                    ("EMIS", "Émis"),
                    ("ACTIF", "Actif"),
                    ("EXPIRE", "Expiré"),
                    ("ANNULE", "Annulé (Complet)"),
                    ("ANNULE_LOCAL", "Annulé (Local uniquement - API à réessayer)"),
                ],
                default="EMIS",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="vehicule",
            name="immatriculation",
            field=models.CharField(
                help_text="Formats valides : DK-0000-H, DK-0000-HA, AA-001-AA, AD-0001, 0001EX, 0001EP01, 001AP0001, 0001-TT-A, CH-000001",
                max_length=20,
                unique=True,
                validators=[contracts.validators.validate_immatriculation],
                verbose_name="Immatriculation",
            ),
        ),
        migrations.AddConstraint(
            model_name="contrat",
            constraint=models.CheckConstraint(
                condition=models.Q(("prime_nette__gte", 0)),
                name="prime_nette_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="contrat",
            constraint=models.CheckConstraint(
                condition=models.Q(("prime_ttc__gte", 0)), name="prime_ttc_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="vehicule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("valeur_neuve__lt", 0), _negated=True),
                    models.Q(("valeur_venale__lt", 0), _negated=True),
                ),
                name="vehicule_valeurs_non_negatives",
            ),
        ),
    ]
