# Generated by Django 5.2.6 on 2025-11-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0002_alter_client_adresse_alter_client_telephone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contrat",
            name="link_facture",
            field=models.URLField(blank=True, null=True),
        ),
    ]
