# Generated by Django 5.2.6 on 2025-10-05 11:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_alter_contrat_status_alter_vehicule_carburant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='Le numéro doit être au format sénégalais (70,75,76,77,78,30,33,34)', regex='^(70|71|75|76|77|78|30|33|34)\\d{7}$')], verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='accessoires',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='askia_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='commission_apporteur',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='commission_askia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='emis_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='fga',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='id_saisie_askia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='net_a_reverser',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='numero_police',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='prime_nette',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='prime_ttc',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='status',
            field=models.CharField(choices=[('SIMULATION', 'Simulation'), ('EMIS', 'Émis'), ('ACTIF', 'Actif'), ('EXPIRE', 'Expiré'), ('ANNULE', 'Annulé')], default='EMIS', max_length=20),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='taxes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
