# Generated by Django 5.2.6 on 2025-11-19 17:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0004_alter_client_telephone"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="telephone_secondaire",
            field=models.CharField(
                blank=True,
                max_length=9,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Le numéro doit être au format sénégalais (ex: 771234567)",
                        regex="^(70|71|75|76|77|78|30|33|34)\\d{7}$",
                    )
                ],
                verbose_name="Téléphone secondaire",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="telephone",
            field=models.CharField(
                db_index=True,
                max_length=9,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Le numéro doit être au format sénégalais (ex: 771234567)",
                        regex="^(70|71|75|76|77|78|30|33|34)\\d{7}$",
                    )
                ],
                verbose_name="Téléphone principal",
            ),
        ),
    ]
