# Generated by Django 5.2.6 on 2025-10-07 13:33

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_alter_client_telephone_alter_contrat_accessoires_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='Le numéro doit être au format sénégalais (70,71,75,76,77,78,30,33,34)', regex='^(70|71|75|76|77|78|30|33|34)\\d{7}$')], verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='duree',
            field=models.PositiveIntegerField(choices=[(1, '1 mois'), (2, '2 mois'), (3, '3 mois'), (6, '6 mois'), (12, '12 mois')], default=12),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='charge_utile',
            field=models.IntegerField(blank=True, help_text='Obligatoire pour les TPC (catégorie 520)', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Charge utile (kg)'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='immatriculation',
            field=models.CharField(help_text='Formats valides : DK-0001-BB, AA-001-AA, AD-0001, 0001EX, 0001EP01, 001AP0001, 0001-TT-A, CH-000001', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message="Format d'immatriculation invalide. Formats acceptés : Régional (DK-0001-BB), Ancien (AA-001-AA), Diplomatique (AD-0001), Export (0001EX, 0001EP01), Apporteur (001AP0001), Transport temporaire (0001-TT-A, AD0001TTA), Étranger (CH-000001)", regex='^((AB|AC|DK|TH|SL|DB|LG|TC|KL|KD|ZG|FK|KF|KG|MT|SD)-?\\d{4}-?[A-Z]{2}|[A-Z]{2}-?\\d{3}-?[A-Z]{2}|AD-?\\d{4}|\\d{4}-?EX|\\d{4}-?EP\\d{2}|\\d{3}-?AP-?\\d{4}|\\d{4}-?TT-?[A-Z]|AD\\d{4}-?TT-?[A-Z]|CH-?\\d{6})$')], verbose_name='Immatriculation'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='sous_categorie',
            field=models.CharField(blank=True, help_text='Obligatoire pour les TPC (catégorie 520)', max_length=3, null=True, verbose_name='Sous-catégorie'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='valeur_neuve',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valeur du véhicule neuf en FCFA', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valeur à neuf'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='valeur_venale',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valeur actuelle du véhicule en FCFA', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valeur vénale'),
        ),
        migrations.AddIndex(
            model_name='contrat',
            index=models.Index(fields=['date_echeance'], name='contracts_c_date_ec_b1e3dd_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicule',
            index=models.Index(fields=['immatriculation'], name='contracts_v_immatri_549d14_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicule',
            index=models.Index(fields=['marque', 'modele'], name='contracts_v_marque_395329_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicule',
            index=models.Index(fields=['categorie'], name='contracts_v_categor_58ebfb_idx'),
        ),
    ]
