# Generated by Django 5.2.6 on 2025-12-02 10:25

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Administrateur"),
                            ("COMMERCIAL", "Commercial"),
                            ("APPORTEUR", "Apporteur d'affaires"),
                        ],
                        default="APPORTEUR",
                        max_length=10,
                        verbose_name="Rôle",
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PLATINE", "Platine - 18% + 2000 FCFA"),
                            ("FREEMIUM", "Freemium - 10% + 1800 FCFA"),
                        ],
                        help_text="Applicable uniquement pour les apporteurs",
                        max_length=10,
                        null=True,
                        verbose_name="Grade",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        db_index=True,
                        max_length=9,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Le numéro doit être au format sénégalais (ex: 771234567)",
                                regex="^(70|71|75|76|77|78|30|33|34)\\d{7}$",
                            )
                        ],
                        verbose_name="Téléphone",
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Adresse")),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière modification"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_users",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
                "ordering": ["-created_at"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="ApporteurOnboarding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("a_lu_et_approuve", models.BooleanField(default=False)),
                ("approuve_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cni_recto",
                    models.FileField(
                        blank=True, null=True, upload_to="onboarding/cni/%Y/%m/"
                    ),
                ),
                (
                    "cni_verso",
                    models.FileField(
                        blank=True, null=True, upload_to="onboarding/cni/%Y/%m/"
                    ),
                ),
                (
                    "signature_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="onboarding/signatures/%Y/%m/"
                    ),
                ),
                (
                    "contrat_pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="onboarding/contrats/%Y/%m/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE_VALIDATION", "En attente de validation"),
                            ("SOUMIS", "Soumis par l'apporteur"),
                            ("VALIDE", "Validé par l'admin"),
                            ("REJETE", "Rejeté"),
                        ],
                        default="EN_ATTENTE_VALIDATION",
                        max_length=24,
                    ),
                ),
                ("version_conditions", models.CharField(default="v1.0", max_length=20)),
                ("ip_accept", models.GenericIPAddressField(blank=True, null=True)),
                ("ua_accept", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Onboarding Apporteur",
                "verbose_name_plural": "Onboardings Apporteurs",
                "ordering": ["-created_at"],
            },
        ),
    ]
