# Generated by Django 5.2.6 on 2025-12-02 13:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apporteuronboarding",
            name="motif_rejet",
            field=models.TextField(
                blank=True, verbose_name="Motif du rejet (si applicable)"
            ),
        ),
        migrations.AlterField(
            model_name="apporteuronboarding",
            name="a_lu_et_approuve",
            field=models.BooleanField(
                default=False, verbose_name="Conditions acceptées"
            ),
        ),
        migrations.AlterField(
            model_name="apporteuronboarding",
            name="approuve_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date d'approbation"
            ),
        ),
        migrations.AlterField(
            model_name="apporteuronboarding",
            name="cni_recto",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="onboarding/cni/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                    )
                ],
                verbose_name="CNI Recto",
            ),
        ),
        migrations.AlterField(
            model_name="apporteuronboarding",
            name="cni_verso",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="onboarding/cni/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                    )
                ],
                verbose_name="CNI Verso",
            ),
        ),
        migrations.AlterField(
            model_name="apporteuronboarding",
            name="contrat_pdf",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="onboarding/contrats/%Y/%m/",
                verbose_name="Contrat généré (PDF)",
            ),
        ),
        migrations.AlterField(
            model_name="apporteuronboarding",
            name="ip_accept",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="IP Acceptation"
            ),
        ),
        migrations.AlterField(
            model_name="apporteuronboarding",
            name="signature_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="onboarding/signatures/%Y/%m/",
                verbose_name="Signature manuscrite",
            ),
        ),
        migrations.AlterField(
            model_name="apporteuronboarding",
            name="status",
            field=models.CharField(
                choices=[
                    ("BROUILLON", "Brouillon / En cours"),
                    ("EN_ATTENTE_VALIDATION", "En attente de validation"),
                    ("VALIDE", "Validé par l'admin"),
                    ("REJETE", "Rejeté (à corriger)"),
                ],
                default="BROUILLON",
                max_length=24,
                verbose_name="Statut du dossier",
            ),
        ),
        migrations.AlterField(
            model_name="apporteuronboarding",
            name="ua_accept",
            field=models.TextField(blank=True, default="", verbose_name="User Agent"),
        ),
    ]
