# Generated by Django 5.2.6 on 2025-09-23 10:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Le numéro doit être au format sénégalais (77/78/76/70/75 suivi de 7 chiffres)', regex='^(77|78|76|70|75)\\d{7}$')], verbose_name='Téléphone'),
        ),
    ]
