# Generated by Django 5.2.6 on 2025-11-10 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                max_length=12,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Le numéro doit être au format sénégalais (ex: 771234567)",
                        regex="^(70|71|75|76|77|78|30|33|34)\\d{7}$",
                    )
                ],
                verbose_name="Téléphone",
            ),
        ),
    ]
