# Generated by Django 5.2.6 on 2025-11-13 10:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_phone"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apporteuronboarding",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Onboarding Apporteur",
                "verbose_name_plural": "Onboardings Apporteurs",
            },
        ),
        migrations.AlterField(
            model_name="apporteuronboarding",
            name="status",
            field=models.CharField(
                choices=[
                    ("EN_ATTENTE_VALIDATION", "En attente de validation"),
                    ("SOUMIS", "Soumis par l'apporteur"),
                    ("VALIDE", "Validé par l'admin"),
                    ("REJETE", "Rejeté"),
                ],
                default="EN_ATTENTE_VALIDATION",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                db_index=True,
                max_length=9,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Le numéro doit être au format sénégalais (ex: 771234567)",
                        regex="^(70|71|75|76|77|78|30|33|34)\\d{7}$",
                    )
                ],
                verbose_name="Téléphone",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrateur"),
                    ("COMMERCIAL", "Commercial"),
                    ("APPORTEUR", "Apporteur d'affaires"),
                ],
                default="APPORTEUR",
                max_length=10,
                verbose_name="Rôle",
            ),
        ),
    ]
